# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cover', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8wNj9ljnY6xwtiTvafIBb852TCwWYVbymNiYchescQnc6kMEz')),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=14)),
                ('correo', models.EmailField(max_length=254)),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profesion')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
    ]
