# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesion',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
